✨ [CollectModal] Update UI with auto-follow flow
likecoin/liker-land pull request #1029
Opened 2023-04-11 15:25 UTC by AuroraHuang22

2023-04-12 03:25 UTC, nwingt reviewed
I think we need a better name for prompt

2023-04-12 03:25 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +        if (this.walletHasLoggedIn) {
can combine these?

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +  UNFOLLOW: 'unFollow', // Show a switch button to toggle follow status.
```suggestion
  UNFOLLOW: 'unfollow', // Show a switch button to toggle follow status.
```

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +const FOLLOW_STATUS = {
```suggestion
const FOLLOW_PROMPT_STATE = {
```

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +  PROMPT: 'prompt', // Show auto-followed UI.
```suggestion
  AUTO: 'auto', // Show auto-followed UI.
```

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +      followStatus: FOLLOW_STATUS.UNFOLLOW,
```suggestion
      followPromptState: FOLLOW_PROMPT_STATE.UNFOLLOW,
```

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +      isFollowStatusChanging: false,
```suggestion
      isFollowPromptUpdating: false,
```

2023-04-12 04:42 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +    followButtonText() {
```suggestion
    followPromptButtonText() {
```

2023-04-12 09:21 UTC, nwingt commented on src/store/modules/wallet.js
> +  walletPromptedList: state => state.interactedCreators,
```suggestion
  walletInteractedCreators: state => state.interactedCreators,
```

2023-04-12 09:21 UTC, nwingt commented on src/store/modules/wallet.js
> +      commit(WALLET_SET_PROMPTED_LIST, []);
```suggestion
      commit(WALLET_SET_INTERACTED_CREATORS, []);
```

2023-04-12 09:21 UTC, nwingt commented on src/store/modules/wallet.js
> +  async walletAddPromptCreator({ state, commit }, creator) {
```suggestion
  async walletAddInteractedCreator({ state, commit }, creator) {
```

2023-04-12 09:21 UTC, nwingt commented on src/store/modules/wallet.js
> +    const prevPromptedList = state.interactedCreators;
```suggestion
    const prevInteractedCreators = state.interactedCreators;
```

2023-04-13 06:32 UTC, nwingt reviewed
Please resolve conflicts too

2023-04-13 06:32 UTC, nwingt commented on src/server/api/routes/users/v2/follow.js
> +      res.json({ followees: [] });
Should be same as below?
```suggestion
      res.json({ interactedCreators: [] });
```

2023-04-13 06:32 UTC, nwingt commented on src/store/modules/wallet.js
> +          ...interactedCreators,
should make sure these are unique?

2023-04-14 06:05 UTC, nwingt commented on src/components/EventModal/Collect/index.vue
> +              name: 'id___en',
Why adding language suffix?
```suggestion
              name: 'id___en',
```

2023-04-17 09:32 UTC, williamchong requested changes

2023-04-17 09:32 UTC, williamchong commented on src/server/api/routes/users/v2/follow.js
> +    res.sendStatus(200);
duplicated
```suggestion
```

2023-04-17 09:32 UTC, williamchong commented on src/server/api/routes/users/v2/follow.js
> +      interactedCreators = [],
How about call them `followees` and `pastFollowees` ?

2023-04-17 09:32 UTC, williamchong commented on src/store/modules/wallet.js
> +  // },
Please remove if not used

2023-04-17 09:32 UTC, williamchong commented on src/store/modules/wallet.js
> +        creator,
Would `state.interactedCreators.concat(creator)` be simpler?

2023-04-17 09:32 UTC, williamchong commented on src/components/EventModal/Collect/index.vue
> +          creator === this.getAddress
Technically `creator === this.getAddress` is not a `followed` relationship, you don't get an email per your own nft mint. Not sure if we should just hide the whole UI here.
but this is design's decision to keep this or not

2023-04-17 09:59 UTC, AuroraHuang22 commented on src/components/EventModal/Collect/index.vue
> +          creator === this.getAddress
Kiu said that when collecting your own work, don't display the "follow" related UI.

2023-04-17 10:06 UTC, williamchong commented on src/components/EventModal/Collect/index.vue
> +          creator === this.getAddress
So state.followed means hidden in this component?

2023-04-17 10:31 UTC, AuroraHuang22 commented on src/components/EventModal/Collect/index.vue
> +          creator === this.getAddress
If state.followed, then display the default UI.. 
Maybe I should change state.followed to state.default.
<img width="248" alt="截圖 2023-04-17 下午6 29 43" src="https://user-images.githubusercontent.com/75730405/232459223-2ffac212-4643-4f29-a17a-f5f6033e5893.png">

2023-04-19 01:14 UTC, nwingt approved these changes

2023-04-19 04:24 UTC, AuroraHuang22 commented
![截圖 2023-04-19 下午12 24 07](https://user-images.githubusercontent.com/75730405/232966646-0bddbe6a-7047-4b01-bbfa-76da0cedacd9.png)
@nwingt

2023-04-19 07:17 UTC, nwingt approved these changes

2023-04-20 03:21 UTC, merged