🎨 Set type as default sorting
likecoin/liker-land pull request #1036
Opened 2023-04-14 07:25 UTC by AuroraHuang22

![網頁擷取_14-4-2023_152053_localhost](https://user-images.githubusercontent.com/75730405/231973123-2c690fb4-1698-4511-88ca-422ed003c573.jpeg)

2023-04-17 15:19 UTC, williamchong commented on src/mixins/portfolio.js
> +        this.nftClassListOfCreatedSorting = NFT_CLASS_LIST_SORTING.TYPE;
We should never have sideeffect in `computed` properties, they should be pure functional
i.e. no `this.xxx = yyy` inside any `computed` functions.

2023-04-19 01:12 UTC, nwingt requested changes

2023-04-19 01:12 UTC, nwingt commented on src/store/modules/nft.js
> +      let YMetaData;
Why using `let`? seems no reassignment

2023-04-19 01:12 UTC, nwingt commented on src/store/modules/nft.js
> +      let YMetaData;
Why using `let`? seems no reassignment

2023-04-19 01:12 UTC, nwingt commented on src/mixins/portfolio.js
> +        (this.nftTypeFilter === 'ALL' &&
```suggestion
        (this.nftTypeFilter === NFT_TYPE_FILTER_OPTIONS.ALL &&
```

2023-04-19 04:33 UTC, williamchong approved these changes

2023-04-19 07:41 UTC, nwingt approved these changes

2023-04-20 03:20 UTC, merged