⚗️ AB test for class page to collect CTA
likecoin/liker-land pull request #1038
Opened 2023-04-19 07:49 UTC by AuroraHuang22

**variant**
![網頁擷取_19-4-2023_15398_localhost](https://user-images.githubusercontent.com/75730405/233005908-41b116ec-3651-40af-a2dd-a98497ce6536.jpeg)

**origin**
![網頁擷取_19-4-2023_154815_localhost](https://user-images.githubusercontent.com/75730405/233005821-9d8cc840-4d64-4efa-a757-c1d05e9b8f40.jpeg)

2023-04-19 08:12 UTC, nwingt requested changes

2023-04-19 08:12 UTC, nwingt commented on src/experiments/class-collect-cta.js
> +    const routeName = parts[0];
I think it is more robust to use `getRouteBaseName()` from context to extract the route name without localization

You may need to inject `getRouteBaseName` from [here](https://github.com/likecoin/liker-land/blob/57c8784c02c880150c75ae10f7c541cb4aa2c6b7/src/mixins/experiment.js#L14) in order to use it

2023-04-19 08:12 UTC, nwingt commented on src/pages/nft/class/_classId/index.vue
> +        })`,
It is better to use a full path without constructing dynamically

2023-04-20 01:56 UTC, nwingt requested changes

2023-04-20 01:56 UTC, nwingt commented on src/mixins/experiment.js
> +          !this.$exp.isEligible({ route: this.getRouteBaseName(this.$route) })
should pass `getRouteBaseName` into `isEligible()` as route is an object with query and params

2023-04-20 01:56 UTC, nwingt commented on src/pages/nft/class/_classId/index.vue
> +    },
I think no need to split, this should be handled with Optimize

2023-04-21 05:08 UTC, nwingt commented on src/mixins/experiment.js
> +            },
```suggestion
            route: {
              name: this.getRouteBaseName(this.$route),
              query: this.$route.query,
              params: this.$route.params,
            },
```
I think this is more simple
```suggestion
            route: {
              ...this.$route,
              name: this.getRouteBaseName(this.$route),
            },
```

2023-04-21 05:49 UTC, nwingt approved these changes

2023-04-21 10:13 UTC, williamchong requested changes

2023-04-21 10:13 UTC, williamchong commented on src/components/NFTCover.vue
> +      v-if="(!isShowVideo && !isShowImage) || !isLoaded"
Is this diff intentional?

2023-04-21 10:34 UTC, AuroraHuang22 commented on src/components/NFTCover.vue
> +      v-if="(!isShowVideo && !isShowImage) || !isLoaded"
Oh, that was unintentional

2023-04-21 10:39 UTC, williamchong approved these changes

2023-04-23 14:29 UTC, merged