📱 Fix in-app notification & improve loading UX
likecoin/liker-land pull request #1045
Opened 2023-04-21 04:54 UTC by nwingt

2023-04-21 05:03 UTC, nwingt commented on src/components/ProgressIndicator.vue
> -      ],
Using an object with key `class` is not flattened with `v-bind`, so I move the class array to separated computed prop

2023-04-21 10:11 UTC, williamchong requested changes

2023-04-21 15:04 UTC, nwingt commented on src/components/AuthRequiredView.vue
> +      <template v-if="isLoadingAtStart || walletIsLoggingIn">
Hmm, my purpose is not hiding connect button, this is solving the blinking UI before `walletIsLoggingIn` changes to `true`, how about `isLoadingStartImmediately`, like the `immediate: true` in watch?

2023-04-21 15:05 UTC, williamchong commented on src/components/AuthRequiredView.vue
> +      <template v-if="isLoadingAtStart || walletIsLoggingIn">
Sounds good to me

2023-04-23 10:00 UTC, nwingt commented on src/components/AuthRequiredView.vue
> +      <template v-if="isLoadingAtStart || walletIsLoggingIn">
Updated

2023-04-23 12:13 UTC, williamchong approved these changes

2023-04-23 13:49 UTC, merged