🚧 Accept predefined email from URL
likecoin/liker-land pull request #1047
Opened 2023-04-21 10:39 UTC by WeiJun0827

<img width="1144" alt="截圖 2023-04-21 下午6 23 14" src="https://user-images.githubusercontent.com/33746295/233615962-285567ac-2a31-47b1-ada9-9e54cf7f2bfe.png">
<img width="1145" alt="截圖 2023-04-21 下午6 23 32" src="https://user-images.githubusercontent.com/33746295/233615971-3afcbe14-38ec-4cff-8858-3c0952788284.png">

Further UI improvement is welcome.
Not sure whether we should also provide some warning sentence, in case of abuse of this mode.

2023-04-22 05:53 UTC, nwingt commented on src/pages/settings/email/index.vue
> +      this.newEmail = this.$route.query.email;
it is more direct to inject it in `data()`

2023-04-24 03:39 UTC, nwingt commented on src/pages/settings/email/index.vue
> +        if (newVal) {
Should check `this.$route.query.email` is not empty too?

2023-04-26 01:52 UTC, nwingt approved these changes

2023-04-26 14:42 UTC, williamchong requested changes

2023-04-26 14:42 UTC, williamchong commented on src/locales/en.json
> +  "settings_email_claim_pending_nft": "We will verify wallet with the email you provided on the previous credit card payment page.",
```suggestion
  "settings_email_claim_pending_nft": "The email you provided during credit card payment will be used for verification.",

```

2023-04-26 14:42 UTC, williamchong commented on src/pages/settings/email/index.vue
> +          this.newEmail = this.$route.query.email;
`this.newEmail = this.$route.query.email;` we can always assign this in data regard less `isClaimingPendingNftMode` or not

2023-04-27 06:35 UTC, williamchong approved these changes

2023-04-27 06:36 UTC, merged