✨ Add component for edition select
likecoin/liker-land pull request #1077
Opened 2023-05-11 08:49 UTC by nwingt

Introduce `<NFTEditionSelect/>`

<img width="950" alt="image" src="https://github.com/likecoin/liker-land/assets/17264716/c0a86ce4-9f9e-4048-bbe0-9116c9d6f2e6">

2023-05-16 19:33 UTC, williamchong requested changes

2023-05-16 19:33 UTC, williamchong commented on src/components/NFTStockLabel.vue
> +      return !this.isSoldOut && this.stock <= 10;
Easy to miss this `10`, suggest to name this number

2023-05-18 03:22 UTC, AuroraHuang22 approved these changes

2023-05-18 08:22 UTC, williamchong approved these changes

2023-05-19 00:47 UTC, merged