✨ [MyDashboard/] Add stakeholder income
likecoin/liker-land pull request #1087
Opened 2023-05-16 13:29 UTC by AuroraHuang22

<img width="1399" alt="截圖 2023-05-16 下午9 09 29" src="https://github.com/likecoin/liker-land/assets/75730405/d2ea01be-bb0d-4ef7-8d6e-d7afc4111c39">
<img width="474" alt="截圖 2023-05-16 下午9 09 20" src="https://github.com/likecoin/liker-land/assets/75730405/2ee8593f-1873-4eb1-888a-90cd4e9f7cd5">

2023-05-16 13:44 UTC, WeiJun0827 commented
@williamchong Do you think I should just integrate querying the user's income into `GET /user-stat`?

2023-05-30 15:07 UTC, williamchong requested changes

2023-05-30 15:07 UTC, williamchong commented on src/components/UserStats/IncomeDetailsDialog.vue
> +          amount: Math.floor(this.totalCommission * nanolike),
Please use bignumber for nanolike => like conversions

2023-05-30 15:07 UTC, williamchong commented on src/components/UserStats/IncomeTable.vue
> +  COMMISSION: 'commission',
Please call this `ROYALTY`

2023-06-05 07:13 UTC, williamchong commented on src/pages/dashboard/index.vue
> +        // no-op
Please `console.error` if error is not expected
or just don't have a `catch` block if the error does not need to be caught

2023-06-05 07:44 UTC, AuroraHuang22 commented
Is this better? @williamchong 
<img width="718" alt="截圖 2023-06-05 下午3 38 56" src="https://github.com/likecoin/liker-land/assets/75730405/55353ed1-0008-4243-a470-58d1e47f81bf">

2023-06-05 07:49 UTC, williamchong commented
> Is this better? @williamchong <img alt="截圖 2023-06-05 下午3 38 56" width="718" src="https://user-images.githubusercontent.com/75730405/243285506-55353ed1-0008-4243-a470-58d1e47f81bf.png">

Can we have the icon with an arrow?
https://mui.com/material-ui/material-icons/?query=new+window&selected=OpenInNew

2023-06-05 08:09 UTC, AuroraHuang22 commented
<img width="783" alt="截圖 2023-06-05 下午4 09 01" src="https://github.com/likecoin/liker-land/assets/75730405/01f78052-377b-45a0-ab17-be89bad0c4fd">

2023-06-05 18:09 UTC, nwingt reviewed
Just code style comments, no big issue 🥳

2023-06-05 18:09 UTC, nwingt commented on src/components/UserStats/IncomeMenuItem.vue
> +        @click="$emit('on-type-click',item.value)"
Vue typically event emitter normally not start with `on` like React 
For example, `onClick` -> `click`

2023-06-05 18:09 UTC, nwingt commented on src/components/UserStats/IncomeDetailsDialog.vue
> +
Just sorting import that group by subfolder
```suggestion
import nftMixin from '~/mixins/nft';

import { logTrackerEvent } from '~/util/EventLogger';
import { convertToLIKEPrice } from '~/util/nft';
import { ellipsis } from '~/util/ui';
```

2023-06-05 18:09 UTC, nwingt commented on src/components/UserStats/MyDashboard.vue
> +    itemStyle() {
should name `itemClasses`?

2023-06-05 18:09 UTC, nwingt commented on src/locales/en.json
> +
Please sort it with JTM

2023-06-05 18:09 UTC, nwingt commented on src/locales/en.json
> +  "nft_portfolio_page_state_royalties": "Total Royalty\n(LIKE)",
Same here, please sort

2023-06-05 18:09 UTC, nwingt commented on src/store/modules/wallet.js
> +  getRoyaltyDetails: state => state.royaltyDetails,
Prefer name not starting with `get` as it is not a function
```suggestion
  walletTotalSales: state => state.totalSales,
  walletTotalRoyalty: state => state.totalRoyalty,
  walletSalesDetails: state => state.salesDetails,
  walletRoyaltyDetails: state => state.royaltyDetails,
```

2023-06-06 01:10 UTC, AuroraHuang22 commented
![截圖 2023-06-06 上午9 10 12](https://github.com/likecoin/liker-land/assets/75730405/3936396f-040c-47f9-a032-ba690405f4c5)

2023-06-06 02:57 UTC, nwingt approved these changes

2023-06-06 02:57 UTC, merged