👽 Connect EditionSelect to the new API
likecoin/liker-land pull request #1108
Opened 2023-06-01 02:30 UTC by AuroraHuang22

![截圖 2023-06-01 上午9 25 29](https://github.com/likecoin/liker-land/assets/75730405/be8ab1f9-da3a-4d76-8d56-53b0fe3eebb4)

2023-06-02 03:17 UTC, nwingt approved these changes

2023-06-02 09:24 UTC, williamchong requested changes

2023-06-02 09:24 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +        this.fetchNFTBookPriceByClassId(this.classId),
So we try to fetch a `book price` for all NFT? Can we safely assume we only have to fetch for those under a `NFT book` collection?

2023-06-02 09:24 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +        window.open(link, '_blank');
```suggestion
        window.open(link, '_blank', 'noopener');
```

2023-06-02 09:24 UTC, williamchong commented on src/mixins/nft.js
> +          ];
If there is no result from `prices` we should just return empty data then disable any UI

2023-06-02 09:24 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +      if (this.getNFTBookStorePricesByClassId(this.classId)) {
Maybe we should add a guard for sold out item

2023-06-02 09:24 UTC, williamchong commented on src/util/api/index.js
> +    form: NFT_BOOK_PLATFORM_LIKER_LAND,
```suggestion
    from: NFT_BOOK_PLATFORM_LIKER_LAND,
```

2023-06-02 09:24 UTC, williamchong commented on src/constant/index.js
> +export const NFT_BOOK_PLATFORM_LIKER_LAND = 'liker_land';
If we expect people to also use likerland as book sales page, we should accept `from` from query string. So this should only act as default value.

2023-06-06 09:54 UTC, nwingt commented
@AuroraHuang22 #1118 is merged, please merge the update & fix on `<NFTEditionSelect/>`

2023-06-06 12:54 UTC, williamchong commented on src/util/api/index.js
> +  platform = NFT_BOOK_PLATFORM_LIKER_LAND,
Please allow nft page to pass value into this param via its query string

2023-06-09 09:23 UTC, williamchong approved these changes

2023-06-14 03:07 UTC, merged