🚸 Add error handling for specific status codes
likecoin/liker-land pull request #1120
Opened 2023-06-07 16:02 UTC by AuroraHuang22

code 38 - nft is already bought
![截圖 2023-06-07 下午11 39 10](https://github.com/likecoin/liker-land/assets/75730405/7c91342d-b994-40df-973e-3f20b2584b52)

code 13 - should show gas related error
![截圖 2023-06-07 下午11 31 01](https://github.com/likecoin/liker-land/assets/75730405/fa6ba9fc-27a7-49b2-a917-0f7c49fcb303)

2023-06-07 16:51 UTC, nwingt commented on src/components/TxModal.vue
> +          logTrackerEvent(this, 'NFT', 'ClickRetry', this.classId, 1);
I suggest to use more specific event name and use snake_case, e.g. `tx_modal_retry_button_clicked`

2023-06-07 16:51 UTC, nwingt commented on src/mixins/nft.js
> +      const errorHandlingByCode = {
suggest to put this in a method 
```js
getErrorHandlerByCode(code) {
  switch (code) {
    case 38:
      return {
        message: 'NFT_IS_ALREADY_BOUGHT',
        runAction: () => this.updateNFTPurchaseInfo();
      };
       
    case 13: 
      return {
        message: 'INSUFFICIENT_GAS_FEE',
      };

    default:
      return {};
  }
}
```

2023-06-07 16:51 UTC, nwingt commented on src/mixins/nft.js
> +          }
```suggestion
          const errorHandler = getErrorHandlerByCode(code)
          if (errorHandler) {
            this.uiSetTxError(errorHandler.message);
            this.uiSetTxStatus(TX_STATUS.FAILED);
            if (typeof errorHandler?.runAction === 'function') {
              errorHandler.runAction();
            }
            return undefined;
          }
```

2023-06-09 00:47 UTC, nwingt approved these changes

2023-06-09 09:20 UTC, williamchong requested changes

2023-06-09 09:20 UTC, williamchong commented on src/locales/en.json
> +  "snackbar_error_nft_is_already_bought": "This NFT has just been collected. Please try purchasing again",
```suggestion
  "snackbar_error_nft_is_already_bought": "This NFT has just been collected by someone else. Please try purchasing again",

```

2023-06-09 09:20 UTC, williamchong commented on src/locales/zh-Hant.json
> +  "snackbar_error_nft_is_already_bought": "此 NFT 剛被收藏了，請再重試購買",
```suggestion
  "snackbar_error_nft_is_already_bought": "此 NFT 剛被其他人收藏了，請再重試購買",

```

2023-06-12 03:34 UTC, williamchong approved these changes

2023-06-12 03:34 UTC, merged