✨ Support purchase multiple email notification
likecoin/liker-land pull request #1162
Opened 2023-06-29 17:34 UTC by nwingt

Depends on https://github.com/likecoin/likecoin-edm/pull/37 & https://github.com/likecoin/likecoin-api-public/pull/485

2023-06-30 04:14 UTC, WeiJun0827 approved these changes

2023-06-30 08:47 UTC, williamchong requested changes

2023-06-30 08:47 UTC, williamchong commented on functions/pubsub/handlers.js
> +        const sellerUserData = userDoc.data();
data() only exists after get() is resolved, so need to be after await

2023-06-30 08:47 UTC, williamchong commented on functions/pubsub/handlers.js
> +      return [classId, nftClassData];
I think nftClassData need to be awaited here if result is an array ? Not sure

2023-07-03 08:48 UTC, williamchong approved these changes

2023-07-06 08:42 UTC, williamchong requested changes

2023-07-06 08:42 UTC, williamchong commented on src/locales/en.json
> +  "portfolio_collect_all_already_alert": "You have already collected all works.",
`You have already collected all the works.`

2023-07-06 09:01 UTC, williamchong approved these changes

2023-07-06 19:28 UTC, williamchong approved these changes

2023-07-07 06:38 UTC, merged