🚸 Enable search text to update creator/tag options
likecoin/liker-land pull request #1173
Opened 2023-07-01 15:43 UTC by AuroraHuang22

- Creator

https://github.com/likecoin/liker-land/assets/75730405/d4e77e9c-48cb-4d23-b36c-56d90fac0470

-Keywords

https://github.com/likecoin/liker-land/assets/75730405/d54ebdb3-467d-45ee-9728-ee41f6404ffd

2023-07-01 17:01 UTC, williamchong requested changes

2023-07-01 17:01 UTC, williamchong commented on src/components/NFTPortfolio/FilterDropdown.vue
> +    filterInputKeywords(keywords) {
Can we use @input instead of watcher?

2023-07-01 17:01 UTC, williamchong commented on src/locales/zh-Hant.json
> +  "order_menu_filter_by_input": "輸入篩選內容",
輸入搜尋內容 seems easier to understand

2023-07-01 17:01 UTC, williamchong commented on src/locales/en.json
> +  "order_menu_filter_by_input": "Enter filtering content",
```suggestion
  "order_menu_filter_by_input": "Enter search keyword",

```

2023-07-03 05:07 UTC, nwingt commented on src/mixins/portfolio.js
> +        });
I think you should iterate with map() first, the above code seems redundant as you use most of the properties

2023-07-03 05:46 UTC, nwingt commented
Keyword is empty [here](https://rinkeby.liker.land/zh-Hant/like1f2k6t98t9kjpdh9v9y95zhmjewuevmuwh82vj0?tab=collected)

<img width="314" alt="image" src="https://github.com/likecoin/liker-land/assets/17264716/5cdffd6a-9851-4aff-a994-c7caf0166c7e">

2023-07-03 14:48 UTC, nwingt commented on src/components/NFTPortfolio/FilterInput.vue
> +        }"
Make code cleaner
```suggestion
      @input="$emit('handle-input-change', $event.target.value)"
```

2023-07-03 15:47 UTC, nwingt commented on src/mixins/portfolio.js
> +        });
```suggestion
        .map(id => {
          const user = this.getUserInfoByAddress(id);
          const likerId = user?.user || id;
          const displayName = user?.displayName || id;
          const avatar = user?.avatar || getIdenticonAvatar(id);
          const isCivicLiker = user?.isSubscribedCivicLiker;
          return { id, likerId, displayName, avatar, isCivicLiker };
        })
        .filter(item => {
          if (!this.nftCreatorInputFilter) return true;

          const lowerCaseInputFilter =
            this.nftCreatorInputFilter.toLowerCase();
          return item.displayName.toLowerCase().includes(lowerCaseInputFilter) ||
            item.likerId.toLowerCase().includes(lowerCaseInputFilter) ||
            item.id.includes(lowerCaseInputFilter);
        });
```

2023-07-04 01:45 UTC, nwingt approved these changes

2023-07-04 02:07 UTC, williamchong approved these changes

2023-07-04 02:10 UTC, merged