[TAS-144]⚗️ [_classId/] AB test for nftBook CTA guidance text
likecoin/liker-land pull request #1250
Opened 2023-07-25 13:18 UTC by AuroraHuang22

2023-07-25 14:23 UTC, williamchong requested changes

2023-07-25 14:23 UTC, williamchong commented on src/experiments/nft-book-cta-text.js
> +    !process.server && route.name === 'nft-class-classId',
```suggestion
    !process.server && route.name,
```
I think better not filter by `route.name === 'nft-class-classId'`, this filter runs on the first page of the session, which could be other pages. We want all collect button to run this exp no matter the first page

2023-07-26 04:22 UTC, williamchong approved these changes

2023-07-26 06:04 UTC, nwingt approved these changes

2023-07-26 06:04 UTC, merged