[TAS-141] ⚡️ Lazy fetch recommendation data
likecoin/liker-land pull request #1285
Opened 2023-08-04 07:04 UTC by AuroraHuang22

**Before**
![截圖 2023-08-04 下午2 50 36（2）](https://github.com/likecoin/liker-land/assets/75730405/77bb0518-4e54-4f8e-9ecf-07898c40c600)
![截圖 2023-08-04 下午2 51 27](https://github.com/likecoin/liker-land/assets/75730405/da517c1a-89f6-402c-9f7a-d0d584b2e626)

**after**
<img width="750" alt="截圖 2023-08-04 下午2 59 27" src="https://github.com/likecoin/liker-land/assets/75730405/b9d2d27b-1838-4855-8615-e3eb497fa656">
<img width="766" alt="截圖 2023-08-04 下午2 59 38" src="https://github.com/likecoin/liker-land/assets/75730405/e68acc84-7d1e-4234-9568-7d12d39ebb0c">

2023-08-04 07:19 UTC, nwingt commented
Can we add a min height for the layout so that it won't collapse when loading causing massive UI shift?

2023-08-04 07:31 UTC, AuroraHuang22 commented
> Can we add a min height for the layout so that it won't collapse when loading causing massive UI shift?

https://github.com/likecoin/liker-land/assets/75730405/19aefe18-65c2-4eac-92d6-31c1a3deb1be

2023-08-14 08:00 UTC, nwingt approved these changes

2023-08-14 09:23 UTC, nwingt requested changes

2023-08-14 09:23 UTC, nwingt commented on src/pages/nft/class/_classId/index.vue
> +          </client-only>
```suggestion
        <client-only>
          <lazy-component
            class="pointer-events-none"
            @show.once="handleFetchRecommendInfo"
          />
        </client-only>
```

2023-08-14 09:24 UTC, merged