[TAS-528] ✨ Support purchasing NFT Book by LIKE
likecoin/liker-land pull request #1405
Opened 2023-11-17 08:39 UTC by WeiJun0827

2023-11-27 07:46 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +      this.$router.push({
Should use .replace()

2023-11-27 08:04 UTC, WeiJun0827 commented on src/pages/nft/class/_classId/index.vue
> +      this.$router.push({
Noted, thanks!!

2023-12-04 09:22 UTC, williamchong requested changes

2023-12-04 09:22 UTC, williamchong commented on src/store/modules/nft.js
> +      } else {
Would just setting the key as `classId_priceIndex` be simpler in structure?

2023-12-04 09:22 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +          await this.fetchNFTPrices();
Should fetch when edition is changed instead of onClick, adding too much delay in user action might cause issue in popup/redirect

2023-12-04 09:22 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +              gaClientId,
Why pop up stripe when `nftPriceInLIKE > 0`?

2023-12-05 13:36 UTC, WeiJun0827 commented on src/pages/nft/class/_classId/index.vue
> +              gaClientId,
Bad logic...

2023-12-05 16:52 UTC, WeiJun0827 commented on src/components/EventModal/Collect/index.vue
> +      email: this.$store.getters.walletEmail || '',
How do we use `this.getAddress`?
I tried use `this.walletEmail` but not work.

2023-12-06 07:46 UTC, williamchong commented on src/components/EventModal/Collect/index.vue
> +      email: this.$store.getters.walletEmail || '',
I think `this.walletEmail` should work..
By not working your mean `this.$store.getters.walletEmail` has value but `this.walletEmail` doesn't?

2023-12-06 07:56 UTC, williamchong requested changes

2023-12-06 07:56 UTC, williamchong commented on src/components/EventModal/Collect/index.vue
> +            if (result && !this.nftIsNFTBook) {
Just check for `result.nftId || result.purchased?.[0]?.nftId` is undefined instead of hardcoding book?

2023-12-06 07:56 UTC, williamchong commented on src/store/modules/nft.js
> +    }
Returning `info` for these function might make them more useful in more scenario

2023-12-06 07:56 UTC, williamchong commented on src/pages/nft/class/_classId/index.vue
> +        }
use `else if` instead of return here might be easier to maintain, since a long block of early returns is harder to read

2023-12-06 07:56 UTC, williamchong commented on src/mixins/nft.js
> +
use `if else` here?

2023-12-06 10:13 UTC, WeiJun0827 commented on src/components/EventModal/Collect/index.vue
> +      email: this.$store.getters.walletEmail || '',
Yes, `this.$store.getters.walletEmail` works but `this.walletEmail` doesn't

2023-12-07 09:47 UTC, williamchong commented on src/store/modules/nft.js
> +    return info;
```suggestion
    let info = getters.getNFTClassPaymentPriceById(classId, priceIndex);
    if (!info) {
      info = await dispatch('fetchNFTBookPaymentPriceInfoByClassIdAndPriceIndex', {
        classId,
        priceIndex,
      });
    }
    return info;
```

2023-12-07 10:06 UTC, merged