📲 Improve mobile version UI for collectorList
likecoin/liker-land pull request #1477
Opened 2023-12-27 03:59 UTC by AuroraHuang22

![截圖 2023-12-27 上午11 57 03](https://github.com/likecoin/liker-land/assets/75730405/9639d3d6-c6e9-459b-b117-e3832f51f7a4)

2023-12-27 19:57 UTC, williamchong approved these changes

2023-12-29 06:26 UTC, nwingt requested changes
Seems the scrolling has issues

https://github.com/likecoin/liker-land/assets/17264716/e01bc370-dd7d-4a08-b2ab-9a89ff65e646



Also, the scrollbar is causing an extra padding
<img width="738" alt="image" src="https://github.com/likecoin/liker-land/assets/17264716/24fd89b0-d8a9-43ee-abd2-a33788ce3970">

2023-12-29 07:33 UTC, AuroraHuang22 commented
[72e2955](https://github.com/likecoin/liker-land/pull/1477/commits/72e29553ce4d6448cb138fe077f93203fd099c78)
https://github.com/likecoin/liker-land/assets/75730405/3d301bc3-1288-45c6-8ab9-a2124242185e

2024-01-02 07:51 UTC, nwingt approved these changes

2024-01-02 07:51 UTC, merged