[TAS-489] ✨ Add UI for discounted LIKE price
likecoin/liker-land pull request #1504
Opened 2024-01-15 15:06 UTC by AuroraHuang22

![截圖 2024-01-16 下午5 54 14](https://github.com/likecoin/liker-land/assets/75730405/236598c3-8290-405e-ad24-716b21c7216b)

2024-01-16 16:04 UTC, williamchong requested changes
Let's treat prediscount is one word here and consistent with API field name

2024-01-16 16:04 UTC, williamchong commented on src/mixins/nft.js
> +    formattedNFTPreDiscountedLIKE() {
```suggestion
    formattedNFTPrediscountedLIKE() {
```

2024-01-16 16:04 UTC, williamchong commented on src/mixins/nft.js
> +    nftPreDiscountedLIKE() {
```suggestion
    nftPrediscountedLIKE() {
```

2024-01-16 16:04 UTC, williamchong commented on src/components/EventModal/Collect/index.vue
> +    },
```suggestion
    discountInfo() {
      if (!this.nftPrediscountedLIKE) {
        return undefined;
      }
      const originalPrice = this.nftPrediscountedLIKE;
      const discountedPrice = this.nftPriceInLIKE;
      if (originalPrice <= discountedPrice) {
        return undefined;
      }

      const discountMultiplier = (discountedPrice / originalPrice) * 100;

      return {
        originalPriceInLIKE: this.formattedNFTPrediscountedLIKE,
        discountPercentage: discountMultiplier.toFixed(0),
      };
    },
```

2024-01-16 16:04 UTC, williamchong commented on src/mixins/nft.js
> +        ? formatNumberWithLIKE(this.nftPreDiscountedLIKE)
```suggestion
        ? formatNumberWithLIKE(this.nftPrediscountedLIKE)
```

2024-01-17 04:15 UTC, williamchong approved these changes

2024-01-17 09:43 UTC, nwingt approved these changes

2024-01-17 09:44 UTC, merged