🥅 Guard invalid claim wallet address
likecoin/liker-land pull request #1506
Opened 2024-01-16 09:37 UTC by AuroraHuang22

![截圖 2024-01-16 下午5 28 41](https://github.com/likecoin/liker-land/assets/75730405/f8c3b4eb-0c28-43b2-95ee-588dd3f7f6ee)

2024-01-16 09:40 UTC, nwingt requested changes
Can we also block the Next button when there is an error?

2024-01-16 09:41 UTC, williamchong requested changes
Should also block next button in onEnterClaimingAddress or with disable

2024-01-16 16:05 UTC, williamchong approved these changes

2024-01-17 06:16 UTC, nwingt approved these changes

2024-01-17 09:06 UTC, merged