🚧 Bootstrap new home page
likecoin/liker-land pull request #1586
Opened 2024-03-27 20:27 UTC by nwingt

2024-04-24 08:08 UTC, williamchong requested changes

2024-04-24 08:08 UTC, williamchong commented on src/pages/index.vue
> +              href="https://blog.like.co/zh/%E5%85%A7%E5%AE%B9%E6%84%9B%E5%A5%BD%E8%80%85%E7%9A%84%E5%BB%A3%E5%A0%B4-liker-land-%E6%96%B0%E5%8A%9F%E8%83%BD/"
Should this be locale sensitive? en version is https://blog.like.co/en/liker-land-the-plaza-for-content-lovers/

2024-04-24 08:08 UTC, williamchong commented on src/layouts/index.vue
> +      }
```suggestion

      if (window.caches) {
        const keyList = await window.caches.keys();
        if (keyList?.length) {
          await Promise.all(
            keyList
              .filter(key => !key.startsWith('reader'))
              .map(key => caches.delete(key))
          );
        }
      }
```

2024-04-24 08:08 UTC, williamchong commented on src/locales/en.json
> +      "a": "網站跟一般電子書無異，主要支援 e-Pub 和 PDF 兩個格式。視乎作者設定，你可以彈性選擇在任何手機，平板，閱讀器線上瀏覽或者下載文本來讀。",
```suggestion
      "a": "網站跟一般電子書無異，主要支援 EPUB 和 PDF 兩個格式。視乎作者設定，你可以彈性選擇在任何手機，平板，閱讀器線上瀏覽或者下載文本來讀。",

```

2024-04-24 08:08 UTC, williamchong commented on src/locales/zh-Hant.json
> +      "a": "每一本電子書都是獨一無二的，並由作者親自簽發。NFT書是可交易的電子書，您可以在Liker Land 書城的市場上將其出售或轉讓給其他人。這為您提供了資產轉換為現金的機會，或者與其他讀者進行交流和交易。",
```suggestion
      "a": "每一本電子書都是獨一無二的，並由作者親自簽發。NFT 書是可交易的電子書，您可以在 Liker Land 書城的市場上將其出售或轉讓給其他人。這為您提供了資產轉換為現金的機會，或者與其他讀者進行交流和交易。",

```

2024-04-24 08:08 UTC, williamchong commented on src/locales/zh-Hant.json
> +      "a": "網站跟一般電子書無異，主要支援 e-Pub 和 PDF 兩個格式。視乎作者設定，你可以彈性選擇在任何手機，平板，閱讀器線上瀏覽或者下載文本來讀。",
```suggestion
      "a": "網站跟一般電子書無異，主要支援 EPUB 和 PDF 兩個格式。視乎作者設定，你可以彈性選擇在任何手機，平板，閱讀器線上瀏覽或者下載文本來讀。",

```

2024-04-24 08:08 UTC, williamchong commented on src/locales/zh-Hant.json
> +  "index_features_title": "Liker Land的特色",
```suggestion
  "index_features_title": "Liker Land 的特色",

```

2024-04-29 07:21 UTC, nwingt commented on src/pages/index.vue
> +        event.stopPropagation();
Updates, requires hacking for Vue router link
https://stackoverflow.com/questions/44815465/how-to-stop-router-link-from-sending-the-user-to-another-page

2024-04-29 09:45 UTC, williamchong requested changes

2024-04-29 10:04 UTC, nwingt commented on src/components/NFTBook/ItemCardV2.vue
> +      :event="isLinkDisabled ? '' : 'click'"
Related to this, cannot use preventDefault to stop navigation without setting event to empty string
https://github.com/likecoin/liker-land/pull/1586#discussion_r1582632883

2024-04-29 10:06 UTC, williamchong approved these changes
Please resolve conflict

2024-04-30 07:47 UTC, AuroraHuang22 approved these changes

2024-05-02 04:37 UTC, williamchong commented on src/pages/index.vue
> -      if (window.scrollY > heroHeight) {
Just set `isHeaderFixed = window.scrollY > heroHeight`?

2024-05-02 04:37 UTC, williamchong commented on src/static/images/og/default-zh.JPG
Extension is JPG instead of jpg?

2024-05-02 04:50 UTC, nwingt commented on src/pages/index.vue
> -      if (window.scrollY > heroHeight) {
Updated

2024-05-02 04:50 UTC, nwingt commented on src/static/images/og/default-zh.JPG
Updated

2024-05-02 06:22 UTC, williamchong approved these changes

2024-05-02 06:40 UTC, merged