✨ Add cross sell dialog
likecoin/liker-land pull request #1734
Opened 2024-08-23 03:21 UTC by nwingt

<img width="501" alt="image" src="https://github.com/user-attachments/assets/6bfa9e21-dd6b-444e-bd61-b22eb0ba0808">

2024-08-23 04:17 UTC, williamchong requested changes

2024-08-23 04:17 UTC, williamchong commented on src/constant/index.js
> +export const CROSS_SELL_PRODUCT_ID = IS_TESTNET
Should be a map of origin id => suggested ids, instead of always enable cross selling

2024-08-23 06:27 UTC, AuroraHuang22 approved these changes

2024-08-23 06:37 UTC, williamchong commented on src/mixins/cross-sell.js
> +      return productIds.length ? productIds[0] : undefined;
Consider filter by existing cart and random index in the future

2024-08-23 06:37 UTC, williamchong commented on src/components/NFTBook/CrossSellDialog.vue
> +        this.addBookProductToShoppingCart({
Not sure if add to cart action should be performed by this dialog or from parent component

2024-08-26 04:59 UTC, williamchong approved these changes

2024-08-26 07:57 UTC, merged