[TAS-2514] 💄Listing page header UI revamp
likecoin/liker-land pull request #1966
Opened 2024-11-24 13:59 UTC by AuroraHuang22

https://github.com/user-attachments/assets/db56f1ab-28f7-442f-b9d5-6a14629b531d

2024-11-26 09:05 UTC, williamchong requested changes
Need to confirm the arrows for tag list on mobile is clickable or swipable

2024-11-28 05:28 UTC, williamchong approved these changes

2024-12-10 10:58 UTC, williamchong requested changes
<img width="576" alt="image" src="https://github.com/user-attachments/assets/f471bac6-b384-446c-8bc5-c24d42b6221f">
Should also implement suggestion in index

<img width="534" alt="image" src="https://github.com/user-attachments/assets/24bf12f0-637d-4945-9cf7-c8207598f9c8">
If I press `Enter` here without typing anything, can we automatically choose the 1st suggested keyword and start the search?

2024-12-11 16:25 UTC, nwingt approved these changes

2024-12-11 16:40 UTC, merged