♻️ Add utm mixin for app download pages
likecoin/liker-land pull request #303
Opened 2020-10-06 10:28 UTC by williamchong

2020-10-06 11:06 UTC, nwingt commented
I suggest adding new computed `utmProps` in `utmMixin` to return `{ utmSource, utm... }`, then u can use `v:bind="utmProps"` for short

2020-10-06 11:08 UTC, williamchong commented
How can I handle cases where one of the field have default value? e.g. `utmMedium: this.utmMedium || 'banner'`

2020-10-06 15:08 UTC, nwingt commented
then I suggest to add method in mixin `getUtmProps({  utmMedium: 'banner' })`

2020-10-07 05:14 UTC, nwingt requested changes

2020-10-07 05:14 UTC, nwingt commented on src/components/CreatorsPage/CreatorsPage.vue
> +            v-bind="this.getUtmProps({ utmMedium: 'creators_page' })"
can omit `this.

2020-10-07 05:14 UTC, nwingt commented on src/pages/getapp.vue
> +        v-bind="this.getUtmProps()"
Can omit `this.`

2020-10-07 05:22 UTC, nwingt approved these changes

2020-10-07 05:23 UTC, merged