Address CL2.0 comments
likecoin/liker-land pull request #347
Opened 2020-12-10 16:01 UTC by nwingt

2020-12-10 17:57 UTC, williamchong commented on src/components/CivicSubscriptionView/CivicSubscriptionView.vue
> +      default: undefined,
Strange decision to not set a default value for state, setting one should always be desirable?
Or maybe we need a state representing "undefined"

2020-12-10 17:57 UTC, williamchong commented on src/pages/_id/index.vue
> +            civicSupport.quantity > 0 &&
`civicSupport && civicSupport.quantity > 0` seems more robust

2020-12-16 13:39 UTC, williamchong requested changes

2020-12-16 13:39 UTC, williamchong commented on src/pages/civic/payment/stripe/success.vue
> +        this.followAuthor(from);
`followAuthor` was not defined in this page's `mapAction`

2020-12-18 06:44 UTC, williamchong requested changes

2020-12-18 06:44 UTC, williamchong commented on src/pages/civic/_from.vue
> -
Sometimes a page without template will cause server error, maybe leave some placeholder template?

2020-12-18 06:44 UTC, williamchong commented on src/components/CreatorsPage/sections/Calculator/Calculator.vue
> +      return this.readersCount * 0.009 + this.readersCount * 0.01;
what is the meaning of this equation? why not `this.readersCount * 0.019` instead?

2020-12-18 09:40 UTC, williamchong approved these changes

2020-12-20 17:17 UTC, williamchong approved these changes

2020-12-21 04:38 UTC, nwingt commented
Merged into master

2020-12-21 04:38 UTC, closed without merging