💄 UI updates for Primitive NFT
likecoin/liker-land pull request #790
Opened 2022-11-19 16:11 UTC by nwingt

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/17264716/202856469-4c64fa74-0929-457b-8043-cd87c19aaa06.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/17264716/202860470-fbd2818d-4f48-43b3-bba2-a10e1e06bda0.png">

2022-11-21 16:48 UTC, williamchong requested changes

2022-11-21 17:07 UTC, nwingt commented on src/pages/_id/index.vue
> +          !this.nftClassListMap?.collected.length
Tried, it doesn't work neither

2022-11-21 17:11 UTC, nwingt commented on src/util/nft.js
> +    case 'ckxpress_book_nft':
```suggestion
```

2022-11-21 17:55 UTC, williamchong approved these changes

2022-11-21 17:56 UTC, williamchong commented on src/pages/_id/index.vue
> +          !this.nftClassListMap?.collected.length
strange, should spend time to investigate when free

2022-11-22 03:14 UTC, merged

2022-11-23 12:40 UTC, WeiJun0827 commented on src/mixins/nft.js
> +    },
Seems some conditional checks in `if (this.isWritingNFT)` should be refactored to `if (this.nftClassCollectionType === nftClassCollectionType.WritingNFT)`?
like [here](https://github.com/likecoin/liker-land/blob/decbf2c249742fa0f073b42c28f77d368a6ddb5c/src/mixins/nft.js#L392)