🚸 [404 page] Update error page layout
likecoin/liker-land pull request #850
Opened 2022-12-21 12:33 UTC by AuroraHuang22

<img width="1439" alt="截圖 2022-12-21 下午7 08 34" src="https://user-images.githubusercontent.com/75730405/208905734-60720e0e-418a-4507-b690-6c3051e56283.png">

2022-12-21 17:16 UTC, williamchong requested changes

2022-12-21 17:16 UTC, williamchong commented on src/locales/en.json
> +  "error_page_not_found_return_back":"Return Back",
```suggestion
  "error_page_not_found_return_back":"Go Back",
```

2022-12-21 17:16 UTC, williamchong commented on src/locales/en.json
> +  "error_page_not_found_description_widget":"Breathe in, and on the out breathe, go back and try again.",
```suggestion
  "error_page_not_found_description_widget":"Breathe in, and on the out breath, go back and try again.",
```

2022-12-21 17:16 UTC, williamchong commented on src/locales/en.json
> +  "error_page_not_found_description":"If you think something is broken, report a problem.",
```suggestion
  "error_page_not_found_description":"If you think something is broken, report an issue.",
```

2022-12-21 17:16 UTC, williamchong commented on src/locales/en.json
> +  "error_page_not_found_report_problem":"Report Problem",
```suggestion
  "error_page_not_found_report_problem":"Report Issue",
```

2022-12-21 17:16 UTC, williamchong commented on src/layouts/error.vue
> +      img-src="/images/error/pageNotFound.svg"
Just put it in `assets/` and use import, no need for static

2022-12-21 17:16 UTC, williamchong commented on src/layouts/error.vue
> +      flex flex-col
```suggestion
      flex
      flex-col
```

2022-12-21 17:16 UTC, williamchong commented on src/layouts/error.vue
> +          href="https://discord.com/channels/763001015712350231/814761730349596712"
I think we can actually trigger crisp
https://github.com/likecoin/liker-land/pull/726

2022-12-22 05:19 UTC, williamchong approved these changes

2022-12-22 13:57 UTC, nwingt commented on src/layouts/error.vue
> +      :price="404"
should return proper error code from `error.statusCode`?

Ref: https://nuxtjs.org/docs/directory-structure/layouts#error-page

2022-12-23 04:32 UTC, nwingt commented on src/layouts/error.vue
> +      errorImg: pageNotFound,
Should error image respect the error code? I think showing 404 img but status code 500 is ambiguous

2022-12-23 05:10 UTC, AuroraHuang22 commented on src/layouts/error.vue
> +      errorImg: pageNotFound,
![截圖 2022-12-23 下午1 07 30](https://user-images.githubusercontent.com/75730405/209275034-9636fe19-5846-48f2-a526-daeaf5d487b3.png)

2022-12-23 05:55 UTC, nwingt approved these changes

2022-12-23 05:55 UTC, nwingt commented on src/layouts/error.vue
> +        :text="$t('error_page_not_found_title')"
Please show error message respect to error code

2022-12-23 07:32 UTC, AuroraHuang22 commented on src/layouts/error.vue
> +        :text="$t('error_page_not_found_title')"
![截圖 2022-12-23 下午3 19 47](https://user-images.githubusercontent.com/75730405/209292393-d066b86e-405e-40ed-acf7-747abfcce2ee.png)

2022-12-23 07:34 UTC, nwingt commented on src/layouts/error.vue
> +        default:
Seem default same as case 4?
```suggestion
        case '4':
        default:
```

2022-12-23 07:39 UTC, AuroraHuang22 commented on src/layouts/error.vue
> +        default:
oh!

2022-12-23 15:52 UTC, nwingt reviewed
Can src/assets/images/error/pageNotFound.png be removed?

2022-12-23 15:53 UTC, nwingt requested changes

2022-12-23 15:53 UTC, nwingt commented on src/locales/en.json
> +  "error_page_not_found_description_widget":"Breathe in, and on the out breath, go back and try again.",
```suggestion
  "error_page_not_found_return_back": "Go Back",
  "error_page_not_found_return_home": "Return Home",
  "error_page_not_found_report_problem": "Report Issue",
  "error_page_not_found_title_404": "Sorry, we could not find that page",
  "error_page_not_found_title_500": "Well, this is unexpected",
  "error_page_not_found_title_widget": "You have found a page that does not exist",
  "error_page_not_found_description_404": "If you think something is broken, report an issue.",
  "error_page_not_found_description_500": "Things are a little unstable here. We will be up and running shortly.",
  "error_page_not_found_description_widget": "Breathe in, and on the out breath, go back and try again.",
```

2022-12-23 16:03 UTC, nwingt commented on src/layouts/error.vue
> +import pageNotFound from '~/assets/images/error/404.svg';
Can `src/assets/images/error/pageNotFound.png` be removed?

2022-12-23 16:25 UTC, nwingt approved these changes
Merry Christmas 🎄

2022-12-23 16:26 UTC, merged