🎨 Format `logType` with camel case
likecoin/liker-land pull request #854
Opened 2022-12-22 06:33 UTC by WeiJun0827

2022-12-22 06:35 UTC, williamchong requested changes

2022-12-22 06:35 UTC, williamchong commented on src/server/api/routes/users/v2/nfts/display-state.js
> +          logType = 'dashboardNFTDisplayStateHide';
```suggestion
          logType = 'DashboardNFTDisplayStateHide';
```

2022-12-22 06:35 UTC, williamchong commented on src/server/api/routes/users/v2/nfts/display-state.js
> +          logType = 'dashboardNFTDisplayStateReset';
```suggestion
          logType = 'DashboardNFTDisplayStateReset';
```

2022-12-22 06:52 UTC, merged

2022-12-23 04:42 UTC, nwingt commented
@WeiJun0827 @williamchong Why changing to camel case?

2022-12-23 07:18 UTC, williamchong commented
> @WeiJun0827 @williamchong Why changing to camel case?

 underscore for ga, Camel for es