✨ [Notifications/] Add notification of mint events with followees
likecoin/liker-land pull request #957
Opened 2023-02-22 14:32 UTC by AuroraHuang22

![截圖 2023-02-22 下午10 21 59](https://user-images.githubusercontent.com/75730405/220651658-c747129a-758c-4ed8-ba92-e26d6844c321.png)
![截圖 2023-02-22 下午10 28 58](https://user-images.githubusercontent.com/75730405/220651697-3735c7a1-0551-413f-86ee-83ad91d9b21a.png)

2023-02-23 02:52 UTC, nwingt approved these changes

2023-02-23 08:47 UTC, williamchong approved these changes

2023-02-23 08:47 UTC, williamchong commented on src/locales/en.json
> +  "event_list_page_event_message_mint_nft": "{fromName} published a new {nftName}.",
```suggestion
  "event_list_page_event_message_mint_nft": "{fromName} just published {nftName}.",

```

2023-02-27 14:02 UTC, williamchong requested changes

2023-02-27 14:02 UTC, williamchong commented on src/store/modules/wallet.js
> +      ),
Please guard the case where `followees` is not an array or is an empty array

2023-02-28 14:30 UTC, nwingt approved these changes

2023-03-01 05:30 UTC, merged