♻️ Refactor routes and correct `/followees` routes
likecoin/liker-land pull request #964
Opened 2023-02-24 08:26 UTC by WeiJun0827

2023-02-24 08:33 UTC, WeiJun0827 commented
Note that users received a verification email for his/her email before deploying this PR but clicking the confirmation link later would encounter an error.
But if users ask to resend another verification email should fix this case.

2023-02-24 18:07 UTC, williamchong requested changes

2023-02-24 18:07 UTC, williamchong commented on src/server/api/routes/users/v2/email.js
> +    console.log(user, email);
Please remove `console.log()`

2023-02-24 18:07 UTC, williamchong commented on src/server/api/routes/users/v2/nfts/display-state.js
> +router.get('/nfts/display-state', async (req, res, next) => {
We do want to keep `/:wallet/` in public endpoints though? Since these are really under some kind of wallet without implicit session

2023-02-24 18:07 UTC, williamchong commented on src/server/api/routes/users/v2/nfts/display-state.js
> +  '/nfts/display-state',
Similarly maybe we should keep `/:wallet` here

2023-02-27 04:34 UTC, williamchong approved these changes

2023-02-28 11:47 UTC, merged