💄 Add NFT Book gem & move to main tab
likecoin/liker-land pull request #979
Opened 2023-03-03 04:08 UTC by AuroraHuang22

![截圖 2023-03-03 上午11 47 46](https://user-images.githubusercontent.com/75730405/222627983-494beb89-782f-4402-9dd8-2dbbb9ab0718.png)

> Since NFT Book is currently sorted at the end, I will open a new PR to add a filter specifically for NFT Book.

<img width="913" alt="截圖 2023-03-03 下午12 00 55" src="https://user-images.githubusercontent.com/75730405/222628260-dc238a6b-7bcf-4022-ba1f-20954e71d229.png">

2023-03-06 08:32 UTC, nwingt commented on src/components/NFTGem/Wrapper.vue
> +      return this.gemLevel === 'book'
I think 'book' should be defined as const

2023-03-06 08:32 UTC, nwingt commented on src/components/NFTGem/Wrapper.vue
> +        ? 'NFT-Book'
Should be localized?

2023-03-06 08:32 UTC, nwingt commented on src/components/NFTGem/Wrapper.vue
> +        case gemLevel <= 16:
??
```suggestion
        case this.gemLevel === 'book':
```

2023-03-06 08:32 UTC, nwingt commented on src/util/nft.js
> +  OTHER: 'Other NFT',
Are these shown directly in UI, I prefer localized them

2023-03-06 08:32 UTC, nwingt commented on src/mixins/portfolio.js
> +            case 'WNFT':
Can we use `NFT_TYPE_OPTIONS.WNFT`?

2023-03-06 08:32 UTC, nwingt commented on src/mixins/portfolio.js
> +      this.nftTypeFilter = NFT_TYPE_OPTIONS.ALL;
Seems more intuitive
```suggestion
      this.nftTypeFilter = NFT_TYPE_FITLER_OPTIONS.ALL;
```

2023-03-06 08:32 UTC, nwingt commented on src/pages/dashboard/index.vue
> +        :portfolio-items-creator-filtering="{ creator: nftCreatorFilter }"
Why object?

2023-03-06 08:32 UTC, nwingt commented on src/util/nft.js
> +export const NFT_TYPE_OPTIONS = {
```suggestion
export const NFT_TYPE_FILTER_OPTIONS = {
```

2023-03-07 03:12 UTC, nwingt commented on src/mixins/portfolio.js
> +    validNftTypeOptions() {
```suggestion
    nftTypeFilteringOptions() {
```

2023-03-07 03:12 UTC, nwingt commented on src/components/NFTPortfolio/MainView.vue
> +    portfolioItemsTypeOptions: {
```suggestion
    portfolioItemsTypeFilteringOptions: {
```

2023-03-07 03:12 UTC, nwingt commented on src/components/NFTPortfolio/MainView.vue
> +      return Object.values(this.portfolioItemsTypeOptions);
I think this list of options should return translated labels
```suggestion
      return Object.values(this.portfolioItemsTypeOptions).map((value) => ({
        value,
        label: this.getPortfolioTypeFilteringLabel(value),
      });
```

2023-03-07 03:13 UTC, nwingt commented
I think this feature can be rebased to master?

2023-03-07 12:34 UTC, AuroraHuang22 commented on src/constant/index.js
> +export const NFT_GEM_NAME_BOOK = 'NFT-Book';
yes, the [gem name](https://github.com/likecoin/liker-land/pull/979/files#diff-1eb6fd5fdfc5858c6d9b5829d6fb4eb0656d0184e9c347292796a40a3feff37bR38) will be shown as tooltip when hovering

2023-03-07 14:01 UTC, williamchong requested changes

2023-03-07 14:01 UTC, williamchong commented on src/mixins/portfolio.js
>          'portfolio',
Since the type always be `creator` now, we just just omit the `type` and hardcode `creator`

2023-03-08 01:19 UTC, nwingt commented on src/mixins/portfolio.js
>      nftClassListOfCreatedExcludedOther() {
Agree

2023-03-08 01:19 UTC, nwingt commented on src/mixins/portfolio.js
>      nftClassListOfCollectedExcludedOther() {
Agree

2023-03-08 01:24 UTC, nwingt reviewed
I saw some BookNFT and NFTBook, it should be latter

2023-03-08 01:24 UTC, nwingt commented on src/mixins/portfolio.js
> +    nftClassMapOfNftBook() {
```suggestion
    nftClassMapOfNFTBook() {
```

2023-03-08 01:24 UTC, nwingt commented on src/util/nft.js
> +export function checkIsNftBook(classMetadata) {
```suggestion
export function checkIsNFTBook(classMetadata) {
```

2023-03-08 02:36 UTC, AuroraHuang22 commented on src/components/NFTPortfolio/MainView.vue
> -
yes

2023-03-08 13:55 UTC, williamchong requested changes

2023-03-08 13:55 UTC, williamchong commented on src/mixins/portfolio.js
>          .reduce((map, nft) => map.set(nft.classId, nft), new Map());
We can build `nftClassMapOfOther` using `nftClassMapOfWritingNft` and `nftClassMapOfNFTBook`

2023-03-09 04:50 UTC, nwingt commented on src/locales/en.json
> +  "filter_menu_creator_selected": "{num} Creator(s)",
Can use `$tc()`
Ref: https://kazupon.github.io/vue-i18n/guide/pluralization.html#pluralization
```suggestion
  "filter_menu_creator_selected": "{num} Creator | {num} Creators",
```

2023-03-09 09:44 UTC, nwingt approved these changes

2023-03-09 09:44 UTC, merged