✨ Improve UX for Liker Land app in-app
likecoin/liker-land pull request #996
Opened 2023-03-10 07:13 UTC by nwingt

Depends on https://github.com/likecoin/likecoin-wallet-connector/pull/18

2023-03-13 10:52 UTC, williamchong requested changes

2023-03-13 10:52 UTC, williamchong commented on src/store/modules/wallet.js
> +    console.log('initIfNecessary', connection);
Please remove `console.log`

2023-03-13 10:52 UTC, williamchong commented on src/store/modules/wallet.js
>    walletIsMatchedSession: (state, getters) =>
Should consider merging these 2 getter in the future

2023-03-13 10:52 UTC, williamchong commented on src/mixins/in-app.js
> +        console.log(
Please remove `console.log`

2023-03-13 10:52 UTC, williamchong commented on src/mixins/in-app.js
> +      return this.$route.query['in-app'] !== undefined || checkIsLikeCoinApp();
Prefer underscore instead of dash for query string

2023-03-13 10:52 UTC, williamchong commented on src/mixins/in-app.js
> +          console.log('openConnectWalletModal', connection);
Please remove `console.log`

2023-03-13 10:52 UTC, williamchong commented on src/mixins/in-app.js
> +          // No-op
We might still want to log the error to console, what are the expected error cases?

2023-03-16 10:20 UTC, williamchong approved these changes

2023-03-27 02:05 UTC, nwingt commented on src/pages/notifications/index.vue
> +    <SettingsPageContentWithAuth
Should rename this component after merging this PR

2023-03-28 00:52 UTC, merged